before:
  hooks:
    - go mod tidy

builds:
  # Linux builds (these can be cross-compiled from Linux)
  - id: linux-amd64
    main: ./cmd/server
    binary: claude-code-pull-worker
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - sql/**/*
      - internal/templates/html/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: upamune
    name: claude-code-pull-worker
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## claude-code-pull-worker {{ .Tag }}

    ### インストール

    ```bash
    # Linux (AMD64)
    curl -L https://github.com/upamune/claude-code-pull-worker/releases/download/{{ .Tag }}/claude-code-pull-worker_{{ .Version }}_linux_amd64.tar.gz | tar xz
    ```